export const navLinks = [
  { id: 'about', title: 'About' },
  { id: 'skills', title: 'Skills' },
  { id: 'experience', title: 'Experience' },
  { id: 'projects', title: 'Projects' },
  { id: 'certifications', title: 'Certifications' },
  { id: 'contact', title: 'Contact' },
]

export const skills = [
  { name: 'C++', abbr: 'C+', color: '#00599C' },
  { name: 'Java', abbr: 'Ja', color: '#ED8B00' },
  { name: 'C', abbr: 'C', color: '#A8B9CC' },
  { name: 'PHP', abbr: 'Ph', color: '#777BB4' },
  { name: 'JavaScript', abbr: 'JS', color: '#F7DF1E' },
  { name: 'React', abbr: 'Re', color: '#61DAFB' },
  { name: 'HTML', abbr: 'HT', color: '#E34F26' },
  { name: 'CSS', abbr: 'CS', color: '#1572B6' },
  { name: 'Tailwind', abbr: 'Tw', color: '#06B6D4' },
  { name: 'Node.js', abbr: 'No', color: '#339933' },
  { name: 'Express', abbr: 'Ex', color: '#aaa6c3' },
  { name: 'MongoDB', abbr: 'Mg', color: '#47A248' },
  { name: 'MySQL', abbr: 'My', color: '#4479A1' },
  { name: 'REST APIs', abbr: 'AP', color: '#FF6C37' },
  { name: 'Git', abbr: 'Gi', color: '#F05032' },
  { name: 'DSA', abbr: 'DS', color: '#915EFF' },
]

export const experiences = [
  {
    title: 'Foundations and Data Structures',
    company: 'CodeSmart',
    date: 'July 2025',
    desc: 'Completed intensive training in Data Structures using C, C++, and Java, developing real-world applications with React and Tailwind CSS, and implementing a custom min-heap for priority-based alert management.',
    color: '#00cea8',
  },
  {
    title: 'Oracle Data Platform Foundations Associate',
    company: 'Oracle Corporation',
    date: 'January 2026',
    desc: 'Earned the Oracle Data Platform 2025 Certified Foundations Associate credential, validating expertise in Oracle cloud data platform fundamentals.',
    color: '#F80000',
  },
  {
    title: 'Cloud Computing — Elite Performer',
    company: 'NPTEL · IIT Kharagpur',
    date: 'October 2025',
    desc: 'Achieved Elite certification with a 71% score in Cloud Computing from IIT Kharagpur. Recognized as a top performer in the cohort.',
    color: '#915EFF',
  },
  {
    title: 'Code-A-Hunt Hackathon — Finalist',
    company: 'Coding Blocks · LPU',
    date: 'February 2024',
    desc: 'Competed against inter-university engineering teams and safely advanced to the semifinals in this competitive hackathon.',
    color: '#bf61ff',
  },
]

export const projects = [
  {
    name: 'Kisan Shayak Platform',
    desc: 'Full-stack agriculture assistance platform built with the MERN stack to provide crop guidance and farming insights. Features a responsive React.js frontend with Tailwind CSS, RESTful APIs with Node.js and Express.js, and an optimized MongoDB database designed for future weather API and crop prediction integration.',
    tags: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Tailwind CSS', 'REST APIs'],
    github: 'https://github.com/MonishKoya',
    live: '',
    color: '#00cea8',
    featured: true,
    image: '/kisan_shayak_banner.png',
  },
  {
    name: 'Agent Connect Platform',
    desc: 'Professional networking platform enabling seamless interaction between agents, clients, and recruiters, improving engagement by 40%. Features profile management, connections, posts, and real-time interactions with MySQL database reducing retrieval time by 30%.',
    tags: ['React.js', 'Node.js', 'Express.js', 'MySQL', 'JavaScript', 'REST APIs'],
    github: 'https://github.com/MonishKoya',
    live: '',
    color: '#915EFF',
    featured: true,
    image: '/agent_connect_banner.png',
  },
  {
    name: 'Restaurant Reservation & Table Management',
    desc: 'Web-based system for digital table booking and reservation management, reducing manual workload by 40%. Features an interactive UI with menu browsing to improve user decision-making before booking, built with pure HTML, CSS, and JavaScript.',
    tags: ['HTML', 'CSS', 'JavaScript', 'UI/UX', 'DOM'],
    github: 'https://github.com/MonishKoya',
    live: '',
    color: '#F7DF1E',
    featured: true,
    image: '/restaurant_reservation_banner.png',
  },
]

export const certifications = [
  {
    title: 'Oracle Data Platform 2025 Certified Foundations Associate',
    issuer: 'Oracle Corporation',
    date: 'Jan 2026',
    abbr: 'OR',
    color: '#F80000',
    bg: 'rgba(248,0,0,0.08)',
    link: '',
  },
  {
    title: 'Cloud Computing — Elite',
    issuer: 'NPTEL · IIT Kharagpur',
    date: 'Oct 2025',
    abbr: 'NP',
    color: '#915EFF',
    bg: 'rgba(145,94,255,0.08)',
    link: '',
  },
  {
    title: 'Responsive Web Design',
    issuer: 'FreeCodeCamp',
    date: 'Dec 2023',
    abbr: 'FC',
    color: '#00cea8',
    bg: 'rgba(0,206,168,0.08)',
    link: '',
  },
  {
    title: 'Foundation in C++ and Java',
    issuer: 'Code-Smart',
    date: 'Jul 2025',
    abbr: 'CS',
    color: '#bf61ff',
    bg: 'rgba(191,97,255,0.08)',
    link: '',
  },
  {
    title: 'Mastering in C',
    issuer: 'CSE Pathshala',
    date: 'Oct 2024',
    abbr: 'CP',
    color: '#F7DF1E',
    bg: 'rgba(247,223,30,0.08)',
    link: '',
  },
  {
    title: 'Code-A-Hunt Hackathon',
    issuer: 'Coding Blocks · LPU',
    date: 'Feb 2024',
    abbr: 'CB',
    color: '#3178C6',
    bg: 'rgba(49,120,198,0.08)',
    link: '',
  },
]
